app = "zing-cdn"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[[services]]
  protocol = "udp"
  internal_port = 34291

  [[services.ports]]
    port = 34291

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 8080

[mounts]
  source = "zing_cdn_data"
  destination = "/data"
