[package]
name = "ZingCDN"
license = "Apache-2.0"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.73.0" }
WAL = { local = "../../../walrus/contracts/wal" }

[addresses]
zing_cdn = "0x0"
